# Set prefix to Ctrl-Space
unbind C-b
set -g prefix C-Space
bind Space send-prefix

# Mouse support
set -g mouse on


# 256 color support
set -g default-terminal "screen-256color"

##########################
### Set Default shell  ###
##########################
# set -g default-command /usr/local/bin/fish
# set -g default-shell /usr/local/bin/fish

######################
###    Plugins     ###
######################
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

