name: User Config
version: 1.0.0.
schema: v1
models:
  - name: GPT 5
    model: gpt-5
    provider: openai
    description: Free openai gpt5 from ch.at
    apiBase: https://ch.at/v1
    default: true
  - name: Ollama Local
    model: llama3.2
    provider: openai
    apiBase: http://localhost:11434/v1
    description: Ollama local models